import { IList } from "./db.model";

export const EdList: Array<IList> = [
    {
        "Title": "A Certain Molestific Mikoto - Express Assault",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000145l"],
        "Related": []
    },
    {
        "Title": "A Virgin Boys Does All He Wants To The Demon Lord's Daughter!",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000146l"],
        "Related": []
    },
    {
        "Title": "Aikata",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000147l", "100000148l"],
        "Related": []
    },
    {
        "Title": "Aka Rin The Cleaner And The Horny Father-in-Law",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000149l"],
        "Related": []
    },
    {
        "Title": "Akuma No Oshigoto",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000150l", "100000151l", "100000152l"],
        "Related": []
    },
    {
        "Title": "Angelita",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000153l"],
        "Related": []
    },
    {
        "Title": "Anorsel A Mysterious Ritual",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000154l"],
        "Related": []
    },
    {
        "Title": "Ariel - Noble Elf Girl Turned Into The Goblin Chief's Sex Slave",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000155l"],
        "Related": []
    },
    {
        "Title": "A's Report",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000156l"],
        "Related": []
    },
    {
        "Title": "At Zanarkand",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000157l"],
        "Related": []
    },
    {
        "Title": "Beautiful Wife With Horrifying Snake Monster",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000158l"],
        "Related": []
    },
    {
        "Title": "Betty's Dream",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000159l"],
        "Related": []
    },
    {
        "Title": "Bloodlust",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000160l", "100000161l"],
        "Related": []
    },
    {
        "Title": "Break Room",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000162l"],
        "Related": []
    },
    {
        "Title": "Bride of the Goblin",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000163l", "100000164l"],
        "Related": []
    },
    {
        "Title": "Captured Black Rescue Mission",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000165l"],
        "Related": []
    },
    {
        "Title": "Chun Li Bound And Disgraced",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000166l"],
        "Related": []
    },
    {
        "Title": "Corporate Training",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000167l", "100000168l"],
        "Related": []
    },
    {
        "Title": "Creepy Nerdy Teacher Gives Sex Education For A Cute Schoolgirl!!",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000169l"],
        "Related": []
    },
    {
        "Title": "D.Va Does Overwatch",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000170l"],
        "Related": []
    },
    {
        "Title": "Dalmascan Night",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000171l"],
        "Related": []
    },
    {
        "Title": "Dangerous Housemates",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000172l"],
        "Related": []
    },
    {
        "Title": "Dark Princess",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000173l"],
        "Related": []
    },
    {
        "Title": "Despicable Dreadful Coach - Pretty Female Student Rape Guidance",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000174l"],
        "Related": []
    },
    {
        "Title": "DobermanS - Diana",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000175l", "100000176l", "100000177l", "100000178l", "100000179l", "100000180l", "100000181l", "100000182l", "100000183l", "100000184l", "100000185l"],
        "Related": []
    },
    {
        "Title": "DobermanS - Eva",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000186l"],
        "Related": []
    },
    {
        "Title": "DobermanS - Kelly",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000187l", "100000188l"],
        "Related": []
    },
    {
        "Title": "DobermanS - Mia",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000189l", "100000190l", "100000191l", "100000192l", "100000193l", "100000194l", "100000195l"],
        "Related": []
    },
    {
        "Title": "DobermanS - Rachel",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000196l", "100000197l", "100000198l"],
        "Related": []
    },
    {
        "Title": "Don't Give Up, Chun-Li!",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000199l"],
        "Related": []
    },
    {
        "Title": "Doree The Explorer",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000200l"],
        "Related": []
    },
    {
        "Title": "Dr Busujima Conspires To Trap A Wife",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000201l"],
        "Related": []
    },
    {
        "Title": "Electro Mask Vs The White Pussy",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000202l"],
        "Related": []
    },
    {
        "Title": "Elven Lust",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000203l"],
        "Related": []
    },
    {
        "Title": "Eralin & Meralin",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000204l"],
        "Related": []
    },
    {
        "Title": "Erotic Gorillaman Takes Revenge On Sexy Catgirl",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000205l"],
        "Related": []
    },
    {
        "Title": "Estrella Girl",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000206l"],
        "Related": []
    },
    {
        "Title": "F.U.T.A. Sentai Squad",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000207l", "100000208l", "100000209l", "100000210l"],
        "Related": []
    },
    {
        "Title": "Fighting Girl Li",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000211l"],
        "Related": []
    },
    {
        "Title": "Final Fuck 7",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000212l", "100000213l", "100000214l", "100000215l", "100000216l", "100000217l", "100000218l", "100000219l", "100000220l", "100000221l", "100000222l", "100000223l"],
        "Related": []
    },
    {
        "Title": "First Assembly",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000224l"],
        "Related": []
    },
    {
        "Title": "Flying High",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000225l"],
        "Related": []
    },
    {
        "Title": "Forbidden Treasure",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000226l"],
        "Related": []
    },
    {
        "Title": "Forbidden Treasure",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000226l"],
        "Related": []
    },
    {
        "Title": "Gakincho Rape",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000227l"],
        "Related": []
    },
    {
        "Title": "Generous Donation",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000228l", "100000229l"],
        "Related": []
    },
    {
        "Title": "Ghosts of Paradise",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000230l"],
        "Related": []
    },
    {
        "Title": "Girl Vs Goddess",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000231l"],
        "Related": []
    },
    {
        "Title": "Girlfriends 4 Ever",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000232l", "100000233l", "100000234l"],
        "Related": []
    },
    {
        "Title": "Golden Saber",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000235l"],
        "Related": []
    },
    {
        "Title": "House of Erotic Horrors",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000236l"],
        "Related": []
    },
    {
        "Title": "Ikedori Daughter",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000237l"],
        "Related": []
    },
    {
        "Title": "Insect Huntress Saki - Hell of Lewd Insects",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000238l"],
        "Related": []
    },
    {
        "Title": "Jackerman - Collection",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": [
            "100000239l", "100000240l", "100000241l", "100000242l", "100000243l", "100000244l", "100000245l", "100000246l", "100000247l", "100000248l", "100000249l", "100000250l", "100000251l", "100000252l",
            "100000253l", "100000254l", "100000255l", "100000256l", "100000257l", "100000258l", "100000259l", "100000260l", "100000261l", "100000262l", "100000263l", "100000264l", "100000265l", "100000266l"
        ],
        "Related": []
    },
    {
        "Title": "Kangoku Hebi-Hime",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000267l"],
        "Related": []
    },
    {
        "Title": "Kasumi - Counterassault Milk Shame Ninja Raping",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000268l"],
        "Related": []
    },
    {
        "Title": "Kunoichi - Broken Princess",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000269l", "100000270l", "100000271l"],
        "Related": []
    },
    {
        "Title": "Let's Play With Karin!",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000272l"],
        "Related": []
    },
    {
        "Title": "Lumina vs Three",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000273l"],
        "Related": []
    },
    {
        "Title": "Mai Shiranui",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000274l"],
        "Related": []
    },
    {
        "Title": "Married Woman Cuckold Video Delivery Beautiful Wife Fitted In A Trap",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000275l"],
        "Related": []
    },
    {
        "Title": "Melody (Strong)",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000276l"],
        "Related": []
    },
    {
        "Title": "Miss Taeko The Beautiful Wife That Gets Cuckolded By Her Father In Law",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000277l"],
        "Related": []
    },
    {
        "Title": "Misspelled",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000278l", "100000279l", "100000280l", "100000281l"],
        "Related": []
    },
    {
        "Title": "Miyako a Beautiful Wife Who is Saddled With Her Husband's Debts And Devoured For Her",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000282l"],
        "Related": []
    },
    {
        "Title": "Moment",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000283l"],
        "Related": []
    },
    {
        "Title": "My Mysterious Girlfriend",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000284l"],
        "Related": []
    },
    {
        "Title": "Netorinbo",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000285l", "100000286l"],
        "Related": []
    },
    {
        "Title": "Nightmare - Code Valentine",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000287l"],
        "Related": []
    },
    {
        "Title": "Noble Elven Knightess - Devilish Juice Excreting Flesh Hole Princess",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000288l"],
        "Related": []
    },
    {
        "Title": "Nympho Laundry",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000289l"],
        "Related": []
    },
    {
        "Title": "Officer On Dick",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000290l"],
        "Related": []
    },
    {
        "Title": "Pan Cakes",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000291l", "100000292l"],
        "Related": []
    },
    {
        "Title": "Prisoner Tifa",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000293l"],
        "Related": []
    },
    {
        "Title": "Project Snow",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000294l"],
        "Related": []
    },
    {
        "Title": "ReADA",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000295l"],
        "Related": []
    },
    {
        "Title": "Red Girl Vs Pig Man",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000296l"],
        "Related": []
    },
    {
        "Title": "Rena Senpai And My Baton",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000297l"],
        "Related": []
    },
    {
        "Title": "Rina and the Hole",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000298l", "100000299l"],
        "Related": []
    },
    {
        "Title": "Ririsu - Hin Chichi Jigokuhen",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000300l"],
        "Related": []
    },
    {
        "Title": "Rohella - Awaken",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000301l"],
        "Related": []
    },
    {
        "Title": "Sailor Mercury - Thrust Into Darkness",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000302l"],
        "Related": []
    },
    {
        "Title": "Sanctuary of Indecent Shame",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000303l"],
        "Related": []
    },
    {
        "Title": "Scarlet Devil Mansion Restraint",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000304l"],
        "Related": []
    },
    {
        "Title": "Secret of Beauty",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000305l", "100000306l", "100000307l", "100000308l"],
        "Related": []
    },
    {
        "Title": "Scarlet Devil Mansion Restraint",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000309l", "100000310l", "100000311l", "100000312l", "100000313l", "100000314l", "100000315l", "100000316l", "100000317l", "100000318l",],
        "Related": []
    },
    {
        "Title": "Severance",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000319l"],
        "Related": []
    },
    {
        "Title": "Sexy Catgirl Thief VS Erotic Gorillaman",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000320l"],
        "Related": []
    },
    {
        "Title": "Shokushu To Onna",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000321l"],
        "Related": []
    },
    {
        "Title": "Siren's Call",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000322l"],
        "Related": []
    },
    {
        "Title": "Space Babe Yukino DX Collector's Edition",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000323l"],
        "Related": []
    },
    {
        "Title": "Spectacled Sensei's Reward Diary",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000324l"],
        "Related": []
    },
    {
        "Title": "Superheroine Imprison Rape",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000325l", "100000326l"],
        "Related": []
    },
    {
        "Title": "Teacher Kaname And Cute Female Student Aoi Provide Guidance On Sexlife",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000327l"],
        "Related": []
    },
    {
        "Title": "The Bordello",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000328l", "100000329l", "100000330l", "100000331l"],
        "Related": []
    },
    {
        "Title": "The Conspiracy of Dr. Busujima",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000332l"],
        "Related": []
    },
    {
        "Title": "The Lust Avenger",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000333l"],
        "Related": []
    },
    {
        "Title": "The Secret Atelier",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000334l"],
        "Related": []
    },
    {
        "Title": "The Seven Realms 3D",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000335l", "100000336l"],
        "Related": []
    },
    {
        "Title": "Tight Fantasy",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000337l", "100000338l"],
        "Related": []
    },
    {
        "Title": "Time To Be Too Erotic And To Dry Does Not-Have",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000339l"],
        "Related": []
    },
    {
        "Title": "Umemaro - Collection",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": [
            "100000340l", "100000341l", "100000342l", "100000343l", "100000344l", "100000345l", "100000346l", "100000347l", "100000348l", "100000349l",
            "100000350l", "100000351l", "100000352l", "100000353l", "100000354l", "100000355l", "100000356l", "100000357l", "100000358l", "100000359l",
            "100000360l", "100000361l", "100000362l", "100000363l", "100000364l", "100000365l", "100000366l"
        ],
        "Related": []
    },
    {
        "Title": "Underpass",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000367l"],
        "Related": []
    },
    {
        "Title": "Velna",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000368l", "100000369l", "100000370l"],
        "Related": []
    },
    {
        "Title": "Virtual Lust Neva",
        "AlternateTitles": [],
        "Descriptions": [],
        "Episodes": 1,
        "Aired": "",
        "Studios": [],
        "Genre": [],
        "Theme": [],
        "Cover": "",
        "ScreenShots": ["100000371l"],
        "Related": []
    }
].sort((a, b) => a.Title.localeCompare(b.Title));